GiftCircle/GiftCircle/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('circulo.urls')),
    path('admin/', admin.site.urls),
]

GiftCircle/circulo/urls.py
from django.urls import path

from . import views

app_name = 'circulo'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),

    path('<int:pk>', views.CirculoView.as_view(), name='circulo'),
    path('persona/<int:pk>', views.PersonaView.as_view(), name='persona'),
    path('deseo/<int:pk>', views.DeseoView.as_view(), name='deseo'),

    path('<int:circulo_id>/enviar_circulo', views.enviar_circulo, name='enviar_circulo'),

    path('nuevo_circulo', views.nuevo_circulo, name='nuevo_circulo'),
    path('<int:circulo_id>/nueva_persona', views.nueva_persona, name='nueva_persona'),
    path('<int:persona_id>/nuevo_deseo', views.nuevo_deseo, name='nuevo_deseo'),

    path('<int:circulo_id>/eliminar_circulo', views.eliminar_circulo, name='eliminar_circulo'),
    path('<int:persona_id>/eliminar_persona', views.eliminar_persona, name='eliminar_persona'),
    path('<int:deseo_id>/eliminar_deseo', views.eliminar_deseo, name='eliminar_deseo'),
]

GiftCircle/circulo/models.py
from django.db import models

# Create your models here.

class Circulo(models.Model):
    nombre    = models.CharField(max_length=200)
    shuffeled = models.BooleanField(default=False)

    def __str__(self):
        return self.nombre


class Persona(models.Model):
    circulo  = models.ForeignKey(Circulo, on_delete=models.CASCADE)
    nombre   = models.CharField(max_length=200)
    telefono = models.CharField(max_length=15, default=None, blank=True, null=True)
    email    = models.EmailField(default=None, blank=True, null=True)

    def __str__(self):
        return self.nombre

    @classmethod
    def create(cls, nombre, telefono="", email=""):
        persona = cls(nombre=nombre, telefono=telefono, email=email)
        return persona


class Deseo(models.Model):
    persona = models.ForeignKey(Persona, on_delete=models.CASCADE)
    deseo   = models.CharField(max_length=200)

    def __str__(self):
        return self.deseo

GiftCircle/circulo/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views import generic
from django.contrib import messages

from .models import Circulo, Persona, Deseo


class IndexView(generic.ListView):
    template_name = 'circulo/index.html'
    context_object_name = 'latest_circulo_list'

    def get_queryset(self):
        """Return the last five circulos."""
        return Circulo.objects.order_by('-nombre')[:5]


class CirculoView(generic.DetailView):
    model = Circulo
    template_name = 'circulo/circulo.html'


class PersonaView(generic.DetailView):
    model = Persona
    template_name = 'circulo/persona.html'


class DeseoView(generic.DetailView):
    model = Deseo
    template_name = 'circulo/deseo.html'


def enviar_circulo(request, circulo_id):
    un_circulo = get_object_or_404(Circulo, pk=circulo_id)
    if not un_circulo.shuffeled:
        if len(un_circulo.persona_set.all()) < 3:
            messages.add_message(request, messages.INFO, 'Debe haber por lo menos tres personas para que el juego valga la pena.')
        else:
            lista = []
            for persona in un_circulo.persona_set.all():
                elem = "{},".format(persona.nombre.replace(","," "))
                for deseo in persona.deseo_set.all():
                    elem += "{};".format(deseo.deseo)
                elem.strip(";")
                if persona.telefono:
                    elem += ",{}".format(persona.telefono)
                elif persona.email:
                    elem += ",{}".format(persona.email)
                lista.append(elem)

            if lista:
                from gift_circle import gift_circle as gf
                gf.enviar(gf.shuffle_data(gf.parse_data(lista)))

                un_circulo.shuffeled = True
                un_circulo.save()

    return HttpResponseRedirect(reverse('circulo:circulo', args=(circulo_id,)))


def nuevo_circulo(request):
    circulo = Circulo(nombre=request.POST['nombre'])
    circulo.save()
    return HttpResponseRedirect(reverse('circulo:index'))


def nueva_persona(request, circulo_id):
    circulo = get_object_or_404(Circulo, pk=circulo_id)

    if not request.POST['telefono'] and not request.POST['email']:
        messages.add_message(request, messages.INFO, 'Debe especificar al menos un medio de contacto.')
    else:
        nombre = Persona(nombre=request.POST['nombre'], telefono=request.POST['telefono'], email=request.POST['email'])
        nombre.circulo = circulo
        nombre.save()

    return HttpResponseRedirect(reverse('circulo:circulo', args=(circulo.id,)))


def nuevo_deseo(request, persona_id):
    persona = get_object_or_404(Persona, pk=persona_id)

    deseo = Deseo(deseo=request.POST['deseo'])
    deseo.persona = persona
    deseo.save()

    return HttpResponseRedirect(reverse('circulo:persona', args=(persona.id,)))


def eliminar_circulo(request, circulo_id):
    circulo = get_object_or_404(Circulo, pk=circulo_id)

    circulo.delete()
    return HttpResponseRedirect(reverse('circulo:index'))


def eliminar_persona(request, persona_id):
    persona = get_object_or_404(Persona, pk=persona_id)

    circulo = persona.circulo
    persona.delete()
    return HttpResponseRedirect(reverse('circulo:circulo', args=(circulo.id,)))


def eliminar_deseo(request, deseo_id):
    deseo = get_object_or_404(Deseo, pk=deseo_id)

    persona = deseo.persona
    deseo.delete()
    return HttpResponseRedirect(reverse('circulo:persona', args=(persona.id,)))

GiftCircle/circulo/templates/circulo/circulo.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'circulo/style.css' %}" />

<h1>{{ circulo.nombre }}</h1>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

{% if circulo.shuffeled %}
  <br /><em>YA FUE ENVIADO</em>
{% endif %}
<ul>
  {% for persona in circulo.persona_set.all %}
    <li><a href="{% url 'circulo:persona' persona.id%}">{{ persona.nombre }}</a></li>
  {% endfor %}
</ul>

{% if not circulo.shuffeled and circulo.persona_set.all|length > 2 %}
<h5>Enviar</h5>
<form action="{% url 'circulo:enviar_circulo' circulo.id %}" method="post">
  {% csrf_token %}
  <input type="submit" value="Enviar Circulo" />
</form>
{% endif %}

<h5>Añadir persona</h5>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'circulo:nueva_persona' circulo.id %}" method="post">
{% csrf_token %}
  <label for="nombre">Nombre</label>
  <input type="text" name="nombre" id="nombre" value="" /><br />

  <label for="telefono">Teléfono</label>
  <input type="text" name="telefono" id="telefono" value="" /><br />

  <label for="temail">EMail</label>
  <input type="text" name="email" id="email" value="" /><br />

  <input type="submit" value="Nueva Persona" />
</form>

<form action="{% url 'circulo:eliminar_circulo' circulo.id %}" method="post">
{% csrf_token %}
  <input type="submit" value="Eliminar Circulo" />
</form>

<a href="{% url 'circulo:index' %}">Inicio</a>

GiftCircle/circulo/templates/circulo/deseo.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'circulo/style.css' %}" />

<h1>{{ deseo.persona.circulo.nombre }}</h1>
<h3>{{ deseo.persona.nombre }}</h3>
<h5>{{ deseo.deseo }}</h5>

<form action="{% url 'circulo:eliminar_deseo' deseo.id %}" method="post">
{% csrf_token %}
  <input type="submit" value="Eliminar Deseo" />
</form>

<a href="{% url 'circulo:persona' deseo.persona.id %}">{{ deseo.persona.nombre }}</a>
<br />
<a href="{% url 'circulo:circulo' deseo.persona.circulo.id %}">{{ deseo.persona.circulo.nombre }}</a>
<br />
<a href="{% url 'circulo:index' %}">Inicio</a>

GiftCircle/circulo/templates/circulo/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'circulo/style.css' %}" />

<h2>Mis círculos de Amigos Secretos</h2>

{% if latest_circulo_list %}
    <ul>
    {% for circulo in latest_circulo_list %}
        <li><a href="{% url 'circulo:circulo' circulo.id %}">{{ circulo.nombre }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No hay circulos disponibles.</p>
{% endif %}

<h5>Añadir circulo</h5>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'circulo:nuevo_circulo' %}" method="post">
{% csrf_token %}
  <label for="nombre">Nombre</label>
  <input type="text" name="nombre" id="nombre" value="" /><br />

  <input type="submit" value="Nuevo Circulo" />
</form>

GiftCircle/circulo/templates/circulo/persona.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'circulo/style.css' %}" />

<h1>{{ persona.circulo.nombre }}</h1>
<h3>{{ persona.nombre }}</h3>
<h5>Contacto</h5>
<ul>
  {% if persona.telefono %}
    <li>Teléfono: {{ persona.telefono }}</li>
  {% endif %}
  {% if persona.email %}
    <li>EMail: {{ persona.email}}</li>
  {% endif %}
</ul>

{% if persona.deseo_set.all|length > 0 %}
<h5>Deseos</h5>
<ul>
  {% for deseo in persona.deseo_set.all %}
    <li><a href="{% url 'circulo:deseo' deseo.id %}">{{ deseo.deseo }}</a></li> 
  {% endfor %}
</ul>
{% endif %}

<h5>Añadir deseo</h5>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'circulo:nuevo_deseo' persona.id %}" method="post">
{% csrf_token %}
  <label for="deseo">Deseo</label>
  <input type="text" name="deseo" id="deseo" value="" /><br />

  <input type="submit" value="Nuevo Deseo" />
</form>

<form action="{% url 'circulo:eliminar_persona' persona.id %}" method="post">
{% csrf_token %}
  <input type="submit" value="Eliminar Persona" />
</form>

<a href="{% url 'circulo:circulo' persona.circulo.id %}">{{ persona.circulo.nombre }}</a>
<br />
<a href="{% url 'circulo:index' %}">Inicio</a>